import UserImg from "./user.png"
import Product1 from "./Product1.jpg"
import Product2 from "./Product2.png"
import Product3 from "./Product3.jpg"
import Product4 from "./Product4.jpg"
import Product5 from "./Product5.jpeg"
import Product6 from "./Product6.jpg"
import Product7 from "./Product7.png"
import Product8 from "./Product8.jpg"
import Product9 from "./Product9.jpg"
import Product10 from "./Product10.jpg"
import Product11 from "./Product11.jpg"
import Product12 from "./Product12.jpeg"
export {UserImg,Product1,Product2,Product3,Product4,Product5,Product6,Product7,Product8,Product9,Product10,Product11,Product12}